# Theme
import = ["~/.config/alacritty/rose-pine-moon.toml"]

[font]
size = 10.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[window]
dynamic_padding = true
decorations = "None"

[window.padding]
x = 4
y = 2

[cursor.style]
blinking = "on"
