# Theme
import = ["~/.config/alacritty/themes/tokyonight_moon.toml"]

[font]
size = 9.0

[font.normal]
family = "JetBrains Mono NerdFont"
style = "Medium"

[font.bold]
family = "JetBrains Mono NerdFont"
style = "Bold"

[window]
dynamic_padding = true
decorations = "None"

[window.padding]
x = 4
y = 2

[cursor.style]
blinking = "on"
